import os
from datetime import datetime, timedelta, timezone
from typing import cast

import pytest

from outlook_skill.calendar import create_calendar_invite, list_calendar_events
from outlook_skill.config import load_settings
from outlook_skill.downloader import download_recent_mail
from outlook_skill.sender import send_mail


pytestmark = pytest.mark.skipif(
    os.getenv("OUTLOOK_ENABLE_LIVE_TESTS") != "1",
    reason="live integration tests are disabled",
)


@pytest.mark.live_integration
def test_live_download_recent_mail_smoke():
    settings = load_settings()
    payload = download_recent_mail(settings, days=1, limit=1)
    assert payload["days"] == 1
    assert "messages" in payload


@pytest.mark.live_integration
def test_live_send_mail_to_self():
    if os.getenv("OUTLOOK_LIVE_ALLOW_SEND") != "1":
        pytest.skip("live send test requires OUTLOOK_LIVE_ALLOW_SEND=1")
    recipient = os.getenv("OUTLOOK_LIVE_TEST_TO") or os.getenv("OUTLOOK_EMAIL")
    if not recipient:
        pytest.skip("live send test requires OUTLOOK_LIVE_TEST_TO or OUTLOOK_EMAIL")

    settings = load_settings()
    timestamp = datetime.now(timezone.utc).isoformat(timespec="seconds")
    subject = f"Outlook skill live send test {timestamp}"
    payload = send_mail(
        settings,
        to=(recipient,),
        subject=subject,
        body_text=f"Live send test generated at {timestamp}.",
    )
    assert payload["sent"] is True

    downloaded = download_recent_mail(settings, days=1, limit=25, folders=("Inbox", "SentItems"))
    messages = cast(list[dict[str, object]], downloaded.get("messages", []))
    subjects = {message.get("subject") for message in messages}
    assert subject in subjects


@pytest.mark.live_integration
def test_live_calendar_invite_to_self():
    if os.getenv("OUTLOOK_LIVE_ALLOW_CALENDAR_INVITE") != "1":
        pytest.skip("live calendar test requires OUTLOOK_LIVE_ALLOW_CALENDAR_INVITE=1")
    attendee = os.getenv("OUTLOOK_LIVE_TEST_CALENDAR_TO") or os.getenv("OUTLOOK_EMAIL")
    if not attendee:
        pytest.skip("live calendar test requires OUTLOOK_LIVE_TEST_CALENDAR_TO or OUTLOOK_EMAIL")

    settings = load_settings()
    now = datetime.now(timezone.utc).replace(microsecond=0)
    start = now + timedelta(days=14)
    end = start + timedelta(minutes=15)
    subject = f"Outlook skill live calendar test {now.isoformat()}"
    payload = create_calendar_invite(
        settings,
        subject=subject,
        start=start.strftime("%Y-%m-%dT%H:%M:%S"),
        end=end.strftime("%Y-%m-%dT%H:%M:%S"),
        timezone="UTC",
        attendees=(attendee,),
        body_text="Live calendar invite test generated by outlook_skill.",
    )
    assert payload["created"] is True
    assert payload["event_id"]


@pytest.mark.live_integration
def test_live_calendar_list():
    settings = load_settings()
    now = datetime.now(timezone.utc)
    start = now.strftime("%Y-%m-%d")
    end_date = (now + timedelta(days=60)).strftime("%Y-%m-%d")
    payload = list_calendar_events(
        settings,
        start_date=start,
        end_date=end_date,
        skip_recurring="daily,weekly",
    )
    assert "events" in payload
    assert isinstance(payload["events"], list)
    assert payload["start_date"] == start
    assert payload["end_date"] == end_date
    assert payload["total_count"] >= payload["shown_count"]
    for event in payload["events"]:
        recurrence = event.get("recurrence_type")
        if recurrence:
            assert recurrence not in ("daily", "weekly")
